* QF Data Verification
This project aims to check spread computation against IPFS of trades published by Quantfury.

* Usage
Nix will automatically handle all dependencies for you. To set it up, you can follow the instructions on the [[https://nixos.org/download.html][official Nix website]]. After the installation, simply run ./verify.sh to execute the script.

You can find the CIDs and passwords of each monthly trading data archive listed on the "TRADING DATA" part of the [[https://qtf.quantfury.com][QTF & QDT Dapp Portal]]. Compare the results from this script with the "Number of trades" and "Spread revenue" listings on the "STATISTICS" tab as part of "QDT TOKENS".

* Note
Specify the list of published trade data archives by defining the CIDs and password in cids_passwords.txt. At the moment, we rely on https://ipfs.quantfury.com/ipfs to download the archive. However, we plan to integrate directly with IPFS in the future.

Currently, the expected results are not automatically checked. This functionality may be added in the future by verifying against the Ethereum transactions for the QDT token.
